### ISSUE TITLE
Chart.Show missing

### ISSUE THREAD

**Issue by forki** [TahaHachana/XPlot#12]
I thried to use XPlot in latest FsLab:

        (*** hide ***)
        #load "packages/FsLab/FsLab.fsx"

        (*** define-output:loading ***)
        open Deedle
        open System.IO
    

        (*** define-output:chart ***)
        open XPlot.GoogleCharts

        let data =
            [
                "Rome", 2761477, 1285.31
                "Milan", 1324110, 181.76
                "Naples", 959574, 117.27
                "Turin", 907563, 130.17
                "Palermo", 655875, 158.9
                "Genoa", 607906, 243.60
                "Bologna", 380181, 140.7
                "Florence", 371282, 102.41
                "Fiumicino", 67370, 213.44
                "Anzio", 52192, 43.43
                "Ciampino", 38262, 11.
            ]

        let options =
            Options(
                region = "IT",
                displayMode = "markers",
                colorAxis = ColorAxis(colors = [|"green"; "blue"|])
            )

        let chart =
            data
            |> Chart.Geo
            |> Chart.WithLabels ["Population"; "Area"]
            |> Chart.WithOptions options
            |> Chart.Show

        (*** include-it:chart ***)

![image](https://cloud.githubusercontent.com/assets/57396/7884298/02c9fc50-061d-11e5-9bc9-118121b62279.png)

/cc @tpetricek

**Comment by TahaHachana** [comment]
Hello Steffen, you don't need the Chart.Show method when working with FsLab. It's now an extension method in a [separate package](XPlot.GoogleCharts.WPF) because, according to Tomas, the WPF bits cause issues on Mac/Linux.

I think the old documentation is confusing you here, I'll try to release the new one this weekend.

**Comment by forki** [comment]
thx

**Comment by forki** [comment]
If I remove the Chart.Show the it crashes with NPE:

![image](https://cloud.githubusercontent.com/assets/57396/7896614/e657e288-06be-11e5-8856-3114ce6a0e4e.png)

**Comment by TahaHachana** [comment]
The "let chart =" line is causing this, delete it and adjust the following block's indentation.

**Comment by forki** [comment]
But then how does it detect what I want to output? I thought it's matched
by name

**Comment by forki** [comment]
it works anyway

**Comment by tpetricek** [comment]
The FsLab API for this is not very nice :-(. There are three commands:

 - `(*** include-it:<snippet-name> ***)` which includes the `it` value (last thing evaluated) from an earlier snippet
 - `(*** include-value:<value-name> ***)` which includes whatever is assigned to the specified F# variable
 - `(*** include-output:<snippet-name> ***)` includes whatever evaluating the snippet printed (and also R outputs)

I would really like to revisit this and have a nicer mechanism (and also documented). It is a bit hard because we need to keep the source as valid F# code. But I suspect we could just have better defaults (automatically embed the most sensible thing).
